### ISSUE TITLE
CSS color preview seems to fail to take into account font size change

### ISSUE THREAD

**Issue by mickaelistria** [mickaelistria/eclipse-bluesky#51]
When I'm using a different font size (Zoom in/out), the color preview box seems misplaced.

![screencast_09-18-2017_03_15_29-pm](https://user-images.githubusercontent.com/469058/30543933-17bba32e-9c85-11e7-8d88-78c31ad52738.gif)

**Comment by mickaelistria** [comment]
cc @angelozerr

**Comment by angelozerr** [comment]
This bug comes from that GlyphMetrics  width which is used to takes place is not updated when there are zoom https://github.com/mickaelistria/eclipse-bluesky/blob/master/org.eclipse.bluesky/src/org/eclipse/bluesky/colors/ColorSymbolSupport.java#L442

Indeed GlyphMetrics   width is updated when StyledText is invalidated (when editor content changes). I have not found solution for the moment.

The code https://github.com/mickaelistria/eclipse-bluesky/blob/master/org.eclipse.bluesky/src/org/eclipse/bluesky/colors/ColorSymbolSupport.java#L423 should be called evry time before paint is done, but I don't know how to do that, because paint listener is done before lines are drawing according my tests.

**Comment by mickaelistria** [comment]
Fixed with #53, thanks @angelozerr !

**Comment by angelozerr** [comment]
Thanks @mickaelistria !
