### ISSUE TITLE
Is this going to be the future of JS/HTML development in Eclipse?

### ISSUE THREAD

**Issue by PhaserEditor2D** [mickaelistria/eclipse-bluesky#62]
Hi, in the next weeks I should start working on the new version of Phaser Editor and I will replace JSDT with something modern. I am evaluating this project and TypeScriptIDE. What I like about this project is that it is fully based on LSP and has no JSDT dependency. However, I do not see too much activity recently.  I am willing to collaborate and continue with the development of this, or is there any other project related to JS/HTML that worths more collaboration? 

@angelozerr 
@mickaelistria

**Comment by mickaelistria** [comment]
The edition part is fully based on LSP.
The debugger is the nodejs debugger binding which is part of JSDT (but doesn't require JSDT editor). At the moment, there is no better alternative we're aware of for JS debugging in Eclipse IDE.

The project is really open for contribution. It can even become an Eclipse.org project if adopters feel there is value for it. Basically, if you want this project to be the future of JS/HTML development in Eclipse IDE and can spend effort on making this happen, it can easily become so since  ;)
That said, it's currently not a project that receives a lot of contributions, even from initial contributors, as the effort are more directed towards other layers of the IDE. But any contribution would be considered with relatively high priority.

**Comment by PhaserEditor2D** [comment]
Thanks for the quick response and info. I will do a try.

**Comment by angelozerr** [comment]
@PhaserEditor2D I would like to move my work for typescript IDE and angular eclipse to bluesky but today there are several missing features like matching brackets, etc which misses. I'm working on those issues with tm4e (language configuration). If one day I can support the whole missing features with lsp (like CodeLens for typescript, compiel on save, etc) I will move to bluesky

**Comment by PhaserEditor2D** [comment]
Hi @angelozerr thanks for sharing your plan.

I will continue pushing in this direction, even if it is not complete. Right now the most important thing about Phaser Editor is the visual designer, so for javascript/typescript programming, a syntax coloring is a start. However, the goal is a complete javascript editor solution, including inline javascript edition and other kind of things useful for game dev.

**Comment by angelozerr** [comment]
> Phaser Editor is the visual designer, so for javascript/typescript programming, a syntax coloring is a start. 

I suggest you to use GenericEditor with tm4e to consume TypeScript TextMate (which is done in eclipse bluesky).

> However, the goal is a complete javascript editor solution, including inline javascript edition and other kind of things useful for game dev.

I think eclipse bluesky is a very good plan for your Phaser Editor. It already support completion, navigation, etc for HTML, JS, CSS and TypeScript. I think once language configuration will be finished (to support match brackets, etc), I think you will have the same feature than JSDT.

**Comment by PhaserEditor2D** [comment]
Yes I agree.

**Comment by PhaserEditor2D** [comment]
By the way, I am really curious about this: https://www.genuitec.com/products/codemix/invite/

**Comment by mickaelistria** [comment]
> By the way, I am really curious about this: https://www.genuitec.com/products/codemix/invite/

So am I. And unfortunately, the company behind the project is usually a very closed, open-source leecher, so it's hard to know more about it.
My guess is that they typically do what this project, Eclipse aCute, Eclipse Corrosion and several other projects do: make language server-based Eclipse IDE plugins, using most often the language-servers that are used in VSCode plugins. I guess they use LSP4E and TM4E too.
Time will tell, but to be honest, I don't expect much innovation nor much technical breakthroughs contributed by this initiative, simply because of the company legacy leeching Eclipse community and extremely rarely contributing anything.

**Comment by angelozerr** [comment]
> make language server-based Eclipse IDE plugins, using most often the language-servers that are used in VSCode plugins. I guess they use LSP4E and TM4E too.

You are describing eclipse-bluesky, no?

**Comment by mickaelistria** [comment]
>
> You are describing eclipse-bluesky, no?
>
No, I'm describing what I think Genuitec's CodeMix is. But indeed, I
imagine it's like a clone of eclipse-bluesky.

**Comment by PhaserEditor2D** [comment]
Yes, for that reason I mentioned it, who knows they forked this.
